[package]
name = "schlandals"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustc-hash = "1.1.0"
clap = { version = "3.0.0-beta.4", features = ["derive"] }
assert_float_eq = "1.1.3"
