# From https://github.com/zjp-CN/mdbook-template
# Simple workflow for deploying static content to GitHub Pages
name: Deploy mdBook
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  workflow_run:
    workflows: ["Mdbook build"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup toolchain update nightly && rustup default nightly
      - run: cargo install mdbook
      - name: Build mdbook
        run: |
          cd doc
          mdbook build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/book/
          force_orphan: true
